
DROP TABLE IF EXISTS `appointment`;
CREATE TABLE `appointment` (
  `appointment_id` varchar(64) NOT NULL COMMENT '预约ID',
  `appointment_no` varchar(64) DEFAULT NULL COMMENT '预约单号',
  `elder_name` varchar(100) DEFAULT NULL COMMENT '老人姓名',
  `elder_id_card` varchar(18) DEFAULT NULL COMMENT '老人身份证号',
  `elder_phone` varchar(11) DEFAULT NULL COMMENT '老人手机号',
  `elder_address` varchar(255) DEFAULT NULL COMMENT '老人地址',
  `elder_area_id` varchar(64) DEFAULT NULL COMMENT '区域ID',
  `elder_area_name` varchar(100) DEFAULT NULL COMMENT '区域名称',
  `service_type` varchar(50) DEFAULT NULL COMMENT '服务类型',
  `service_type_code` varchar(20) DEFAULT NULL COMMENT '服务类型编码',
  `service_content` varchar(255) DEFAULT NULL COMMENT '服务内容',
  `appointment_time` varchar(50) DEFAULT NULL COMMENT '预约时间',
  `service_duration` int DEFAULT NULL COMMENT '预计服务时长(分钟)',
  `provider_id` varchar(64) DEFAULT NULL COMMENT '服务机构ID',
  `provider_name` varchar(200) DEFAULT NULL COMMENT '服务机构名称',
  `provider_address` varchar(255) DEFAULT NULL COMMENT '服务机构地址',
  `visitor_count` int DEFAULT NULL COMMENT '来访人数',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `status` varchar(20) DEFAULT 'PENDING' COMMENT '状态',
  `validity` varchar(20) DEFAULT 'VALID' COMMENT '数据有效性',
  `cancel_reason` varchar(255) DEFAULT NULL COMMENT '取消原因',
  `reply_info` varchar(255) DEFAULT NULL COMMENT '回复信息',
  `assessment_type` varchar(50) DEFAULT NULL COMMENT '评估类型',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `confirm_time` datetime DEFAULT NULL COMMENT '确认时间',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '逻辑删除',
  `order_id` varchar(32) DEFAULT NULL COMMENT '关联订单ID',
  `order_no` varchar(50) DEFAULT NULL COMMENT '关联订单号',
  PRIMARY KEY (`appointment_id`),
  UNIQUE KEY `uk_appointment_no` (`appointment_no`),
  KEY `idx_elder_phone` (`elder_phone`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='预约管理表';
DROP TABLE IF EXISTS `quality_check`;
CREATE TABLE `quality_check` (
  `quality_check_id` varchar(64) NOT NULL COMMENT '质检ID',
  `check_no` varchar(64) DEFAULT NULL COMMENT '质检编号',
  `order_id` varchar(64) DEFAULT NULL COMMENT '订单ID',
  `order_no` varchar(64) DEFAULT NULL COMMENT '订单号',
  `service_log_id` varchar(64) DEFAULT NULL COMMENT '服务日志ID',
  `service_category` varchar(50) DEFAULT NULL COMMENT '服务类别',
  `provider_id` varchar(64) DEFAULT NULL COMMENT '服务商ID',
  `provider_name` varchar(200) DEFAULT NULL COMMENT '服务商名称',
  `staff_id` varchar(64) DEFAULT NULL COMMENT '服务人员ID',
  `staff_name` varchar(100) DEFAULT NULL COMMENT '服务人员姓名',
  `check_type` varchar(20) DEFAULT NULL COMMENT '质检类型',
  `check_method` varchar(20) DEFAULT NULL COMMENT '质检方式',
  `check_score` decimal(5,2) DEFAULT NULL COMMENT '综合评分',
  `check_result` varchar(20) DEFAULT NULL COMMENT '质检结果',
  `check_photos` text COMMENT '质检照片',
  `check_remark` varchar(500) DEFAULT NULL COMMENT '质检备注',
  `check_time` datetime DEFAULT NULL COMMENT '质检时间',
  `checker_id` varchar(64) DEFAULT NULL COMMENT '质检员ID',
  `checker_name` varchar(100) DEFAULT NULL COMMENT '质检员姓名',
  `need_rectify` tinyint(1) DEFAULT '0' COMMENT '是否需要整改',
  `rectify_notice` varchar(255) DEFAULT NULL COMMENT '整改通知',
  `rectify_deadline` datetime DEFAULT NULL COMMENT '整改期限',
  `rectify_status` varchar(20) DEFAULT NULL COMMENT '整改状态',
  `rectify_photos` text COMMENT '整改照片',
  `rectify_remark` varchar(500) DEFAULT NULL COMMENT '整改说明',
  `recheck_time` datetime DEFAULT NULL COMMENT '复检时间',
  `recheck_result` varchar(20) DEFAULT NULL COMMENT '复检结果',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '逻辑删除',
  PRIMARY KEY (`quality_check_id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_provider_id` (`provider_id`),
  KEY `idx_check_result` (`check_result`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='服务质检表';
DROP TABLE IF EXISTS `service_log`;
CREATE TABLE `service_log` (
  `service_log_id` varchar(64) NOT NULL COMMENT '服务日志ID',
  `log_no` varchar(64) DEFAULT NULL COMMENT '服务日志编号',
  `order_id` varchar(64) DEFAULT NULL COMMENT '订单ID',
  `order_no` varchar(64) DEFAULT NULL COMMENT '订单号',
  `elder_id` varchar(64) DEFAULT NULL COMMENT '老人ID',
  `elder_name` varchar(100) DEFAULT NULL COMMENT '老人姓名',
  `elder_phone` varchar(11) DEFAULT NULL COMMENT '老人手机号',
  `elder_address` varchar(255) DEFAULT NULL COMMENT '老人地址',
  `staff_id` varchar(64) DEFAULT NULL COMMENT '服务人员ID',
  `staff_name` varchar(100) DEFAULT NULL COMMENT '服务人员姓名',
  `staff_phone` varchar(11) DEFAULT NULL COMMENT '服务人员手机号',
  `provider_id` varchar(64) DEFAULT NULL COMMENT '服务商ID',
  `provider_name` varchar(200) DEFAULT NULL COMMENT '服务商名称',
  `service_type_code` varchar(20) DEFAULT NULL COMMENT '服务类型编码',
  `service_type_name` varchar(100) DEFAULT NULL COMMENT '服务类型名称',
  `service_date` varchar(20) DEFAULT NULL COMMENT '服务日期',
  `service_start_time` datetime DEFAULT NULL COMMENT '服务开始时间',
  `service_end_time` datetime DEFAULT NULL COMMENT '服务结束时间',
  `service_duration` int DEFAULT NULL COMMENT '服务时长(分钟)',
  `service_status` varchar(20) DEFAULT NULL COMMENT '服务状态',
  `actual_duration` int DEFAULT NULL COMMENT '实际服务时长',
  `service_score` decimal(5,2) DEFAULT NULL COMMENT '服务评分',
  `service_comment` varchar(500) DEFAULT NULL COMMENT '服务评价',
  `service_photos` text COMMENT '服务照片',
  `elder_signature` varchar(255) DEFAULT NULL COMMENT '老人签名',
  `anomaly_type` varchar(50) DEFAULT NULL COMMENT '异常类型',
  `anomaly_desc` varchar(500) DEFAULT NULL COMMENT '异常描述',
  `anomaly_photos` text COMMENT '异常照片',
  `anomaly_status` varchar(20) DEFAULT NULL COMMENT '异常处理状态',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '逻辑删除',
  `sign_in_time` datetime DEFAULT NULL COMMENT '签到时间',
  `sign_out_time` datetime DEFAULT NULL COMMENT '签退时间',
  `review_time` datetime DEFAULT NULL COMMENT '审核时间',
  `reviewer_id` varchar(32) DEFAULT NULL COMMENT '审核人ID',
  `reviewer_name` varchar(50) DEFAULT NULL COMMENT '审核人姓名',
  `review_comment` varchar(500) DEFAULT NULL COMMENT '审核意见',
  `audit_status` varchar(20) DEFAULT NULL COMMENT '审核状态',
  `health_observations` text COMMENT '健康观察',
  PRIMARY KEY (`service_log_id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_staff_id` (`staff_id`),
  KEY `idx_provider_id` (`provider_id`),
  KEY `idx_service_date` (`service_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='服务日志表';
DROP TABLE IF EXISTS `t_area`;
CREATE TABLE `t_area` (
  `area_id` varchar(32) NOT NULL COMMENT '区域ID',
  `area_code` varchar(50) NOT NULL COMMENT '区域编码',
  `area_name` varchar(100) DEFAULT NULL COMMENT '区域名称',
  `parent_id` varchar(32) DEFAULT NULL COMMENT '父区域ID',
  `area_level` varchar(20) DEFAULT NULL COMMENT '区域层级 PROVINCE/CITY/DISTRICT/STREET/COMMUNITY',
  `longitude` decimal(10,6) DEFAULT NULL COMMENT '经度',
  `latitude` decimal(10,6) DEFAULT NULL COMMENT '纬度',
  `sort_order` int DEFAULT NULL COMMENT '排序',
  `status` varchar(20) DEFAULT 'ACTIVE' COMMENT '状态',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`area_id`),
  UNIQUE KEY `area_code` (`area_code`),
  KEY `idx_parent` (`parent_id`),
  KEY `idx_area_code` (`area_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='区域表';
DROP TABLE IF EXISTS `t_customer_feedback`;
CREATE TABLE `t_customer_feedback` (
  `feedback_id` varchar(32) NOT NULL COMMENT '反馈ID',
  `elder_id` varchar(32) DEFAULT NULL COMMENT '老人ID',
  `feedback_type` varchar(20) DEFAULT NULL COMMENT '反馈类型 COMPLAINT/SUGGESTION/PRAISE',
  `feedback_content` text COMMENT '反馈内容',
  `feedback_date` date DEFAULT NULL COMMENT '反馈日期',
  `feedback_channel` varchar(20) DEFAULT NULL COMMENT '反馈渠道 ONLINE/PHONE/ON_SITE',
  `feedback_attachments` text COMMENT '反馈附件',
  `handler_id` varchar(32) DEFAULT NULL COMMENT '处理人ID',
  `handling_status` varchar(20) DEFAULT 'PENDING' COMMENT '处理状态 PENDING/HANDLING/HANDLED',
  `handling_result` text COMMENT '处理结果',
  `handling_time` datetime DEFAULT NULL COMMENT '处理时间',
  `feedback_response` text COMMENT '回复内容',
  `satisfaction` int DEFAULT NULL COMMENT '满意度(1-5星)',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`feedback_id`),
  KEY `idx_elder` (`elder_id`),
  KEY `idx_feedback_type` (`feedback_type`),
  KEY `idx_handling_status` (`handling_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户反馈表';
DROP TABLE IF EXISTS `t_dict_item`;
CREATE TABLE `t_dict_item` (
  `dict_item_id` varchar(32) NOT NULL,
  `dict_type_id` varchar(32) NOT NULL COMMENT '字典类型ID',
  `dict_item_code` varchar(50) DEFAULT NULL COMMENT '字典项编码',
  `dict_item_name` varchar(100) DEFAULT NULL COMMENT '字典项名称',
  `dict_item_value` varchar(100) DEFAULT NULL COMMENT '字典项值',
  `sort_order` int DEFAULT NULL COMMENT '排序',
  `status` varchar(20) DEFAULT 'NORMAL' COMMENT '状态',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`dict_item_id`),
  KEY `idx_dict_type` (`dict_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='数据字典项表';
DROP TABLE IF EXISTS `t_dict_type`;
CREATE TABLE `t_dict_type` (
  `dict_type_id` varchar(32) NOT NULL COMMENT '字典类型ID',
  `dict_type_code` varchar(50) NOT NULL COMMENT '字典类型编码',
  `dict_type_name` varchar(100) DEFAULT NULL COMMENT '字典类型名称',
  `dict_type_desc` varchar(500) DEFAULT NULL COMMENT '字典类型描述',
  `is_system` tinyint DEFAULT '0' COMMENT '是否系统字典',
  `sort_order` int DEFAULT NULL COMMENT '排序',
  `status` varchar(20) DEFAULT 'NORMAL' COMMENT '状态',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`dict_type_id`),
  UNIQUE KEY `dict_type_code` (`dict_type_code`),
  KEY `idx_dict_type_code` (`dict_type_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='数据字典类型表';
DROP TABLE IF EXISTS `t_elder`;
CREATE TABLE `t_elder` (
  `elder_id` varchar(32) NOT NULL COMMENT '老人ID',
  `elder_no` varchar(50) DEFAULT NULL COMMENT '老人编号',
  `elder_name` varchar(50) NOT NULL COMMENT '姓名',
  `gender` varchar(10) DEFAULT NULL COMMENT '性别 MALE/FEMALE',
  `birth_date` date DEFAULT NULL COMMENT '出生日期',
  `age` int DEFAULT NULL COMMENT '年龄',
  `id_card` varchar(18) DEFAULT NULL COMMENT '身份证号',
  `phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `ethnicity` varchar(20) DEFAULT '汉族' COMMENT '民族',
  `education` varchar(20) DEFAULT NULL COMMENT '学历',
  `marital_status` varchar(20) DEFAULT NULL COMMENT '婚姻状况',
  `political_status` varchar(20) DEFAULT NULL COMMENT '政治面貌',
  `photo_url` varchar(500) DEFAULT NULL COMMENT '个人照片',
  `status` varchar(20) DEFAULT 'ACTIVE' COMMENT '状态 ACTIVE/TRANSFERRED/DECEASED',
  `register_date` date DEFAULT NULL COMMENT '建档日期',
  `address` varchar(500) DEFAULT NULL COMMENT '居住地址',
  `area_id` varchar(32) DEFAULT NULL COMMENT '所属区域ID',
  `care_level` varchar(20) DEFAULT 'NORMAL' COMMENT '护理级别 NORMAL/MILD/MODERATE/SEVERE',
  `living_status` varchar(20) DEFAULT NULL COMMENT '居住状况 ALONE/WITH_FAMILY/NURSING_HOME',
  `health_status` varchar(20) DEFAULT 'FAIR' COMMENT '健康状况 GOOD/FAIR/POOR',
  `care_type` varchar(20) DEFAULT 'HOME' COMMENT '养老类型 HOME-居家/COMMUNITY-社区/INSTITUTION-机构',
  `emergency_contact` varchar(100) DEFAULT NULL COMMENT '紧急联系人',
  `emergency_phone` varchar(20) DEFAULT NULL COMMENT '紧急联系电话',
  `tenant_id` varchar(32) DEFAULT NULL COMMENT '租户ID',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  `provider_id` varchar(32) DEFAULT NULL COMMENT '服务商ID',
  `provider_name` varchar(200) DEFAULT NULL COMMENT '服务商名称',
  `area_name` varchar(100) DEFAULT NULL COMMENT '区域名称',
  PRIMARY KEY (`elder_id`),
  UNIQUE KEY `elder_no` (`elder_no`),
  KEY `idx_elder_no` (`elder_no`),
  KEY `idx_name` (`elder_name`),
  KEY `idx_id_card` (`id_card`),
  KEY `idx_phone` (`phone`),
  KEY `idx_area` (`area_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='老人基本信息表';
DROP TABLE IF EXISTS `t_elder_demand`;
CREATE TABLE `t_elder_demand` (
  `demand_id` varchar(32) NOT NULL,
  `elder_id` varchar(32) NOT NULL COMMENT '老人ID',
  `service_type_code` varchar(20) DEFAULT NULL COMMENT '服务类型编码',
  `service_type_name` varchar(100) DEFAULT NULL COMMENT '服务类型名称',
  `demand_priority` varchar(20) DEFAULT 'MEDIUM' COMMENT '优先级 HIGH/MEDIUM/LOW',
  `service_frequency` varchar(20) DEFAULT NULL COMMENT '服务频次 ONCE/WEEKLY/MONTHLY',
  `preferred_time` varchar(50) DEFAULT NULL COMMENT '服务时间偏好',
  `estimated_duration` int DEFAULT NULL COMMENT '预计服务时长',
  `special_requirements` text COMMENT '特殊要求',
  `demand_status` varchar(20) DEFAULT 'ACTIVE' COMMENT '需求状态 ACTIVE/INACTIVE',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`demand_id`),
  KEY `idx_elder` (`elder_id`),
  KEY `idx_service_type` (`service_type_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='老人服务需求表';
DROP TABLE IF EXISTS `t_elder_family`;
CREATE TABLE `t_elder_family` (
  `family_id` varchar(32) NOT NULL,
  `elder_id` varchar(32) NOT NULL COMMENT '老人ID',
  `family_type` varchar(20) DEFAULT NULL COMMENT '家庭关系类型',
  `family_name` varchar(50) DEFAULT NULL COMMENT '家属姓名',
  `family_phone` varchar(20) DEFAULT NULL COMMENT '家属电话',
  `family_address` varchar(500) DEFAULT NULL COMMENT '家属地址',
  `is_caretaker` tinyint DEFAULT '0' COMMENT '是否主要照顾人',
  `is_emergency_contact` tinyint DEFAULT '0' COMMENT '是否紧急联系人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`family_id`),
  KEY `idx_elder` (`elder_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='老人家庭信息表';
DROP TABLE IF EXISTS `t_elder_health`;
CREATE TABLE `t_elder_health` (
  `health_id` varchar(32) NOT NULL,
  `elder_id` varchar(32) NOT NULL COMMENT '老人ID',
  `blood_type` varchar(10) DEFAULT NULL COMMENT '血型',
  `height` decimal(5,2) DEFAULT NULL COMMENT '身高',
  `weight` decimal(5,2) DEFAULT NULL COMMENT '体重',
  `medical_history` text COMMENT '病史记录',
  `medication_list` text COMMENT '用药清单',
  `allergy_history` text COMMENT '过敏史',
  `chronic_diseases` text COMMENT '慢性病',
  `disabilities` text COMMENT '残疾情况',
  `self_care_ability` varchar(20) DEFAULT NULL COMMENT '自理能力',
  `care_level` varchar(20) DEFAULT NULL COMMENT '照护等级',
  `last_checkup_date` date DEFAULT NULL COMMENT '上次体检日期',
  `checkup_report_url` varchar(500) DEFAULT NULL COMMENT '体检报告',
  `health_status` varchar(50) DEFAULT NULL COMMENT '健康状况',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`health_id`),
  UNIQUE KEY `uk_elder` (`elder_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='老人健康信息表';
DROP TABLE IF EXISTS `t_elder_subsidy`;
CREATE TABLE `t_elder_subsidy` (
  `subsidy_id` varchar(32) NOT NULL,
  `elder_id` varchar(32) NOT NULL COMMENT '老人ID',
  `subsidy_type` varchar(50) DEFAULT NULL COMMENT '补贴类型 GOVERNMENT/SELF_PAY/MIXED',
  `subsidy_name` varchar(100) DEFAULT NULL COMMENT '补贴名称',
  `subsidy_standard` decimal(10,2) DEFAULT NULL COMMENT '补贴标准',
  `subsidy_quota` decimal(10,2) DEFAULT NULL COMMENT '补贴额度',
  `subsidy_balance` decimal(10,2) DEFAULT NULL COMMENT '补贴余额',
  `subsidy_start_date` date DEFAULT NULL COMMENT '补贴开始日期',
  `subsidy_end_date` date DEFAULT NULL COMMENT '补贴结束日期',
  `subsidy_status` varchar(20) DEFAULT 'ACTIVE' COMMENT '补贴状态 ACTIVE/SUSPENDED/EXPIRED',
  `approval_time` datetime DEFAULT NULL COMMENT '审批通过时间',
  `approver_id` varchar(32) DEFAULT NULL COMMENT '审批人ID',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`subsidy_id`),
  KEY `idx_elder` (`elder_id`),
  KEY `idx_subsidy_type` (`subsidy_type`),
  KEY `idx_status` (`subsidy_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='老人补贴表';
DROP TABLE IF EXISTS `t_login_log`;
CREATE TABLE `t_login_log` (
  `login_log_id` varchar(32) NOT NULL,
  `user_id` varchar(32) DEFAULT NULL COMMENT '用户ID',
  `username` varchar(50) DEFAULT NULL COMMENT '用户名',
  `login_time` datetime DEFAULT NULL COMMENT '登录时间',
  `login_ip` varchar(50) DEFAULT NULL COMMENT '登录IP',
  `login_location` varchar(200) DEFAULT NULL COMMENT '登录地点',
  `login_device` varchar(200) DEFAULT NULL COMMENT '登录设备',
  `login_status` varchar(20) DEFAULT NULL COMMENT '登录状态 SUCCESS/FAIL',
  `fail_reason` varchar(500) DEFAULT NULL COMMENT '失败原因',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`login_log_id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_login_time` (`login_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='登录日志表';
DROP TABLE IF EXISTS `t_menu`;
CREATE TABLE `t_menu` (
  `menu_id` varchar(64) NOT NULL COMMENT '菜单ID',
  `menu_code` varchar(128) NOT NULL COMMENT '菜单代码(路由name)',
  `menu_name` varchar(64) NOT NULL COMMENT '菜单名称',
  `parent_id` varchar(64) DEFAULT NULL COMMENT '父菜单ID',
  `menu_type` varchar(32) DEFAULT 'MENU' COMMENT '类型 MENU/BUTTON',
  `path` varchar(255) DEFAULT NULL COMMENT '路由路径',
  `component` varchar(255) DEFAULT NULL COMMENT '组件路径',
  `icon` varchar(128) DEFAULT NULL COMMENT '图标',
  `order_num` int DEFAULT '0' COMMENT '排序',
  `is_hidden` tinyint DEFAULT '0' COMMENT '是否隐藏 0-否 1-是',
  `status` varchar(32) DEFAULT 'NORMAL' COMMENT '状态',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0',
  PRIMARY KEY (`menu_id`),
  UNIQUE KEY `menu_code` (`menu_code`),
  KEY `idx_parent_id` (`parent_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='菜单表';
DROP TABLE IF EXISTS `t_operation_log`;
CREATE TABLE `t_operation_log` (
  `operation_log_id` varchar(32) NOT NULL,
  `user_id` varchar(32) DEFAULT NULL COMMENT '用户ID',
  `username` varchar(50) DEFAULT NULL COMMENT '用户名',
  `operation_module` varchar(50) DEFAULT NULL COMMENT '操作模块',
  `operation_type` varchar(50) DEFAULT NULL COMMENT '操作类型',
  `operation_content` text COMMENT '操作内容',
  `operation_time` datetime DEFAULT NULL COMMENT '操作时间',
  `ip_address` varchar(50) DEFAULT NULL COMMENT 'IP地址',
  `request_method` varchar(10) DEFAULT NULL COMMENT '请求方法',
  `request_url` varchar(500) DEFAULT NULL COMMENT '请求URL',
  `request_params` text COMMENT '请求参数',
  `response_result` text COMMENT '响应结果',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`operation_log_id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_operation_time` (`operation_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='操作日志表';
DROP TABLE IF EXISTS `t_order`;
CREATE TABLE `t_order` (
  `order_id` varchar(32) NOT NULL COMMENT '订单ID',
  `order_no` varchar(50) NOT NULL COMMENT '订单编号',
  `elder_id` varchar(32) NOT NULL COMMENT '老人ID',
  `elder_name` varchar(50) DEFAULT NULL COMMENT '老人姓名',
  `elder_phone` varchar(20) DEFAULT NULL COMMENT '老人电话',
  `elder_address` varchar(500) DEFAULT NULL COMMENT '老人地址',
  `service_type_code` varchar(20) NOT NULL COMMENT '服务类型编码',
  `service_type_name` varchar(100) DEFAULT NULL COMMENT '服务类型名称',
  `service_date` date DEFAULT NULL COMMENT '服务日期',
  `service_time` varchar(10) DEFAULT NULL COMMENT '服务时间',
  `service_duration` int DEFAULT NULL COMMENT '预计服务时长(分钟)',
  `service_address` varchar(500) DEFAULT NULL COMMENT '服务地址',
  `longitude` varchar(20) DEFAULT NULL COMMENT '经度',
  `latitude` varchar(20) DEFAULT NULL COMMENT '纬度',
  `special_requirements` text COMMENT '特殊要求',
  `order_type` varchar(20) DEFAULT 'NORMAL' COMMENT '订单类型 NORMAL/URGENT',
  `order_source` varchar(20) DEFAULT NULL COMMENT '订单来源 COMMUNITY/ELDER/FAMILY',
  `subsidy_type` varchar(20) DEFAULT NULL COMMENT '补贴类型',
  `estimated_price` decimal(10,2) DEFAULT NULL COMMENT '预计价格',
  `subsidy_amount` decimal(10,2) DEFAULT NULL COMMENT '补贴金额',
  `self_pay_amount` decimal(10,2) DEFAULT NULL COMMENT '自付金额',
  `actual_price` decimal(10,2) DEFAULT NULL COMMENT '实际价格',
  `status` varchar(20) DEFAULT 'CREATED' COMMENT '订单状态',
  `provider_id` varchar(32) DEFAULT NULL COMMENT '服务商ID',
  `staff_id` varchar(32) DEFAULT NULL COMMENT '服务人员ID',
  `community_id` varchar(32) DEFAULT NULL COMMENT '社区ID',
  `tenant_id` varchar(32) DEFAULT NULL COMMENT '租户ID',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`order_id`),
  UNIQUE KEY `order_no` (`order_no`),
  KEY `idx_order_no` (`order_no`),
  KEY `idx_elder` (`elder_id`),
  KEY `idx_status` (`status`),
  KEY `idx_service_date` (`service_date`),
  KEY `idx_provider` (`provider_id`),
  KEY `idx_staff` (`staff_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单表';
DROP TABLE IF EXISTS `t_order_dispatch`;
CREATE TABLE `t_order_dispatch` (
  `dispatch_id` varchar(32) NOT NULL,
  `order_id` varchar(32) NOT NULL COMMENT '订单ID',
  `provider_id` varchar(32) NOT NULL COMMENT '服务商ID',
  `staff_id` varchar(32) DEFAULT NULL COMMENT '服务人员ID',
  `dispatch_time` datetime DEFAULT NULL COMMENT '派单时间',
  `dispatcher_id` varchar(32) DEFAULT NULL COMMENT '派单人ID',
  `dispatch_type` varchar(20) DEFAULT NULL COMMENT '派单类型 MANUAL/AUTO/GRAB',
  `dispatch_status` varchar(20) DEFAULT 'PENDING' COMMENT '派单状态 PENDING/RECEIVED/REJECTED',
  `receive_time` datetime DEFAULT NULL COMMENT '接单时间',
  `reject_reason` varchar(500) DEFAULT NULL COMMENT '拒绝理由',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`dispatch_id`),
  KEY `idx_order` (`order_id`),
  KEY `idx_provider` (`provider_id`),
  KEY `idx_staff` (`staff_id`),
  KEY `idx_status` (`dispatch_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单派单记录表';
DROP TABLE IF EXISTS `t_permission`;
CREATE TABLE `t_permission` (
  `permission_id` varchar(32) NOT NULL COMMENT '权限ID',
  `permission_code` varchar(100) NOT NULL COMMENT '权限编码',
  `permission_name` varchar(100) NOT NULL COMMENT '权限名称',
  `permission_type` varchar(20) DEFAULT NULL COMMENT '权限类型 CATALOG/MENU/BUTTON',
  `parent_id` varchar(32) DEFAULT '0' COMMENT '父权限ID',
  `permission_url` varchar(500) DEFAULT NULL COMMENT '权限URL',
  `permission_method` varchar(10) DEFAULT NULL COMMENT '请求方法',
  `sort_order` int DEFAULT NULL COMMENT '排序',
  `icon` varchar(200) DEFAULT NULL COMMENT '图标',
  `status` varchar(20) DEFAULT 'NORMAL' COMMENT '状态',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`permission_id`),
  UNIQUE KEY `permission_code` (`permission_code`),
  KEY `idx_parent` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='权限表';
DROP TABLE IF EXISTS `t_provider`;
CREATE TABLE `t_provider` (
  `provider_id` varchar(32) NOT NULL COMMENT '服务商ID',
  `provider_no` varchar(50) DEFAULT NULL COMMENT '服务商编号',
  `provider_name` varchar(200) NOT NULL COMMENT '企业名称',
  `provider_type` varchar(20) DEFAULT NULL COMMENT '服务商类型 GOVERNMENT/PRIVATE/NON_PROFIT',
  `credit_code` varchar(18) DEFAULT NULL COMMENT '统一社会信用代码',
  `legal_person` varchar(50) DEFAULT NULL COMMENT '法定代表人',
  `legal_person_phone` varchar(20) DEFAULT NULL COMMENT '法定代表人电话',
  `register_address` varchar(500) DEFAULT NULL COMMENT '注册地址',
  `business_address` varchar(500) DEFAULT NULL COMMENT '经营地址',
  `contact_person` varchar(50) DEFAULT NULL COMMENT '联系人',
  `contact_phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `contact_email` varchar(100) DEFAULT NULL COMMENT '联系邮箱',
  `service_scope` text COMMENT '服务范围',
  `staff_size` int DEFAULT NULL COMMENT '人员规模',
  `credit_level` varchar(10) DEFAULT NULL COMMENT '信用等级 AAA/AA/A/B/C',
  `credit_score` decimal(5,2) DEFAULT '100.00' COMMENT '信用得分',
  `business_license` varchar(500) DEFAULT NULL COMMENT '营业执照',
  `status` varchar(20) DEFAULT 'PENDING' COMMENT '状态 PENDING/APPROVED/REJECTED/SUSPENDED',
  `audit_comment` varchar(500) DEFAULT NULL COMMENT '审核备注',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `auditor_id` varchar(32) DEFAULT NULL COMMENT '审核人ID',
  `tenant_id` varchar(32) DEFAULT NULL COMMENT '租户ID',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  `rating` decimal(3,2) DEFAULT '0.00' COMMENT '评分',
  `rating_count` int DEFAULT '0' COMMENT '评价次数',
  PRIMARY KEY (`provider_id`),
  UNIQUE KEY `provider_no` (`provider_no`),
  KEY `idx_provider_no` (`provider_no`),
  KEY `idx_credit_code` (`credit_code`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='服务商信息表';
DROP TABLE IF EXISTS `t_provider_qualification`;
CREATE TABLE `t_provider_qualification` (
  `qualification_id` varchar(32) NOT NULL,
  `provider_id` varchar(32) NOT NULL COMMENT '服务商ID',
  `qualification_type` varchar(50) DEFAULT NULL COMMENT '资质类型',
  `qualification_name` varchar(200) DEFAULT NULL COMMENT '资质名称',
  `qualification_number` varchar(100) DEFAULT NULL COMMENT '资质编号',
  `issue_date` date DEFAULT NULL COMMENT '发证日期',
  `expiry_date` date DEFAULT NULL COMMENT '有效期至',
  `issue_organization` varchar(200) DEFAULT NULL COMMENT '发证机构',
  `attachment_url` varchar(500) DEFAULT NULL COMMENT '附件URL',
  `status` varchar(20) DEFAULT 'VALID' COMMENT '状态 VALID/EXPIRED',
  `audit_status` varchar(20) DEFAULT 'APPROVED' COMMENT '审核状态',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`qualification_id`),
  KEY `idx_provider` (`provider_id`),
  KEY `idx_expiry` (`expiry_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='服务商资质表';
DROP TABLE IF EXISTS `t_provider_service_type`;
CREATE TABLE `t_provider_service_type` (
  `provider_service_id` varchar(32) NOT NULL,
  `provider_id` varchar(32) NOT NULL,
  `service_type_code` varchar(20) NOT NULL,
  `service_type_name` varchar(100) NOT NULL,
  `service_price` decimal(10,2) DEFAULT NULL COMMENT '服务价格',
  `subsidy_price` decimal(10,2) DEFAULT NULL COMMENT '补贴价格',
  `service_area` varchar(500) DEFAULT NULL COMMENT '服务区域',
  `status` varchar(20) DEFAULT 'ACTIVE' COMMENT '状态',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`provider_service_id`),
  KEY `idx_provider` (`provider_id`),
  KEY `idx_service_type` (`service_type_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='服务商服务类型表';
DROP TABLE IF EXISTS `t_refund`;
CREATE TABLE `t_refund` (
  `refund_id` varchar(32) NOT NULL COMMENT '退款ID',
  `refund_no` varchar(50) DEFAULT NULL COMMENT '退款编号',
  `order_id` varchar(32) NOT NULL COMMENT '订单ID',
  `settlement_id` varchar(32) DEFAULT NULL COMMENT '结算ID',
  `refund_type` varchar(20) DEFAULT NULL COMMENT '退款类型 FULL/PARTIAL',
  `refund_amount` decimal(10,2) DEFAULT NULL COMMENT '退款金额',
  `refund_reason` varchar(500) DEFAULT NULL COMMENT '退款原因',
  `refund_status` varchar(20) DEFAULT 'PENDING' COMMENT '退款状态 PENDING/PROCESSING/COMPLETED/REJECTED',
  `applicant_id` varchar(32) DEFAULT NULL COMMENT '申请人ID',
  `approver_id` varchar(32) DEFAULT NULL COMMENT '审批人ID',
  `approval_time` datetime DEFAULT NULL COMMENT '审批时间',
  `refund_time` datetime DEFAULT NULL COMMENT '退款时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`refund_id`),
  UNIQUE KEY `refund_no` (`refund_no`),
  KEY `idx_order` (`order_id`),
  KEY `idx_status` (`refund_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='退款记录表';
DROP TABLE IF EXISTS `t_role`;
CREATE TABLE `t_role` (
  `role_id` varchar(32) NOT NULL COMMENT '角色ID',
  `role_code` varchar(50) NOT NULL COMMENT '角色编码',
  `role_name` varchar(100) NOT NULL COMMENT '角色名称',
  `role_desc` varchar(500) DEFAULT NULL COMMENT '角色描述',
  `role_type` varchar(20) DEFAULT NULL COMMENT '角色类型',
  `data_scope` varchar(20) DEFAULT 'ALL' COMMENT '数据范围 ALL/DEPT/DEPT_CHILDREN/SELF',
  `sort_order` int DEFAULT NULL COMMENT '排序',
  `status` varchar(20) DEFAULT 'NORMAL' COMMENT '状态',
  `tenant_id` varchar(32) DEFAULT NULL COMMENT '租户ID',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`role_id`),
  UNIQUE KEY `role_code` (`role_code`),
  KEY `idx_role_code` (`role_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色表';
DROP TABLE IF EXISTS `t_role_menu`;
CREATE TABLE `t_role_menu` (
  `role_menu_id` varchar(64) NOT NULL COMMENT '主键',
  `role_id` varchar(64) NOT NULL COMMENT '角色ID',
  `menu_id` varchar(64) NOT NULL COMMENT '菜单ID',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`role_menu_id`),
  UNIQUE KEY `uk_role_menu` (`role_id`,`menu_id`),
  KEY `idx_role_id` (`role_id`),
  KEY `idx_menu_id` (`menu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色菜单关联表';
DROP TABLE IF EXISTS `t_role_permission`;
CREATE TABLE `t_role_permission` (
  `role_permission_id` varchar(32) NOT NULL,
  `role_id` varchar(32) NOT NULL COMMENT '角色ID',
  `permission_id` varchar(32) NOT NULL COMMENT '权限ID',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`role_permission_id`),
  KEY `idx_role` (`role_id`),
  KEY `idx_permission` (`permission_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色权限关联表';
DROP TABLE IF EXISTS `t_service_evaluation`;
CREATE TABLE `t_service_evaluation` (
  `evaluation_id` varchar(32) NOT NULL COMMENT '评价ID',
  `order_id` varchar(32) NOT NULL COMMENT '订单ID',
  `staff_id` varchar(32) NOT NULL COMMENT '服务人员ID',
  `provider_id` varchar(32) NOT NULL COMMENT '服务商ID',
  `elder_id` varchar(32) DEFAULT NULL COMMENT '老人ID',
  `attitude_score` int DEFAULT NULL COMMENT '态度得分(1-5星)',
  `quality_score` int DEFAULT NULL COMMENT '质量得分(1-5星)',
  `efficiency_score` int DEFAULT NULL COMMENT '效率得分(1-5星)',
  `overall_score` int DEFAULT NULL COMMENT '总体得分(1-5星)',
  `average_score` decimal(5,2) DEFAULT NULL COMMENT '平均得分',
  `evaluation_content` text COMMENT '评价内容',
  `evaluation_tags` varchar(500) DEFAULT NULL COMMENT '评价标签',
  `is_anonymous` tinyint DEFAULT '0' COMMENT '是否匿名',
  `evaluation_time` datetime DEFAULT NULL COMMENT '评价时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  `evaluation_token` varchar(128) DEFAULT NULL COMMENT '评价邀请Token',
  `token_status` varchar(20) DEFAULT 'PENDING' COMMENT 'Token状态',
  `token_expire_time` datetime DEFAULT NULL COMMENT 'Token过期时间',
  `token_used_time` datetime DEFAULT NULL COMMENT 'Token使用时间',
  `token_used_ip` varchar(50) DEFAULT NULL COMMENT '提交IP',
  `quality_check_id` varchar(32) DEFAULT NULL COMMENT '关联质检单ID',
  `service_log_id` varchar(32) DEFAULT NULL COMMENT '关联服务日志ID',
  `reply_content` varchar(500) DEFAULT NULL COMMENT '回复内容',
  `reply_time` datetime DEFAULT NULL COMMENT '回复时间',
  `replyer_id` varchar(32) DEFAULT NULL COMMENT '回复人ID',
  `replyer_name` varchar(50) DEFAULT NULL COMMENT '回复人姓名',
  PRIMARY KEY (`evaluation_id`),
  KEY `idx_order` (`order_id`),
  KEY `idx_staff` (`staff_id`),
  KEY `idx_provider` (`provider_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='服务评价表';
DROP TABLE IF EXISTS `t_service_price`;
CREATE TABLE `t_service_price` (
  `price_id` varchar(32) NOT NULL COMMENT '定价ID',
  `service_type_code` varchar(20) NOT NULL COMMENT '服务类型编码',
  `service_type_name` varchar(100) DEFAULT NULL COMMENT '服务类型名称',
  `price_unit` varchar(20) DEFAULT NULL COMMENT '计价单位',
  `standard_price` decimal(10,2) DEFAULT NULL COMMENT '标准价格',
  `government_price` decimal(10,2) DEFAULT NULL COMMENT '政府指导价',
  `subsidy_price` decimal(10,2) DEFAULT NULL COMMENT '补贴价格',
  `area_id` varchar(32) DEFAULT NULL COMMENT '适用区域',
  `effective_date` date DEFAULT NULL COMMENT '生效日期',
  `expiry_date` date DEFAULT NULL COMMENT '失效日期',
  `status` varchar(20) DEFAULT 'ACTIVE' COMMENT '状态',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`price_id`),
  KEY `idx_service_type` (`service_type_code`),
  KEY `idx_area` (`area_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='服务定价表';
DROP TABLE IF EXISTS `t_service_record`;
CREATE TABLE `t_service_record` (
  `service_record_id` varchar(32) NOT NULL,
  `order_id` varchar(32) NOT NULL,
  `staff_id` varchar(32) NOT NULL,
  `elder_id` varchar(32) DEFAULT NULL COMMENT '老人ID',
  `service_date` date DEFAULT NULL COMMENT '服务日期',
  `check_in_time` datetime DEFAULT NULL COMMENT '签到时间',
  `check_out_time` datetime DEFAULT NULL COMMENT '签退时间',
  `service_duration` int DEFAULT NULL COMMENT '实际服务时长',
  `check_in_location` varchar(500) DEFAULT NULL COMMENT '签到位置',
  `check_out_location` varchar(500) DEFAULT NULL COMMENT '签退位置',
  `service_photos` text COMMENT '服务照片',
  `service_log` text COMMENT '服务日志',
  `elder_feedback` text COMMENT '老人反馈',
  `service_status` varchar(20) DEFAULT NULL COMMENT '服务状态',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`service_record_id`),
  KEY `idx_order` (`order_id`),
  KEY `idx_staff` (`staff_id`),
  KEY `idx_date` (`service_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='服务记录表';
DROP TABLE IF EXISTS `t_service_type`;
CREATE TABLE `t_service_type` (
  `service_type_id` varchar(32) NOT NULL COMMENT '服务类型ID',
  `service_type_code` varchar(50) NOT NULL COMMENT '服务类型编码',
  `service_type_name` varchar(100) DEFAULT NULL COMMENT '服务类型名称',
  `parent_id` varchar(32) DEFAULT NULL COMMENT '父类型ID',
  `service_level` varchar(20) DEFAULT NULL COMMENT '服务层级',
  `service_desc` text COMMENT '服务描述',
  `service_standard` text COMMENT '服务标准',
  `service_unit` varchar(20) DEFAULT NULL COMMENT '计价单位',
  `estimated_duration` int DEFAULT NULL COMMENT '预计服务时长(分钟)',
  `icon` varchar(200) DEFAULT NULL COMMENT '图标',
  `sort_order` int DEFAULT NULL COMMENT '排序',
  `status` varchar(20) DEFAULT 'ACTIVE' COMMENT '状态',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`service_type_id`),
  UNIQUE KEY `service_type_code` (`service_type_code`),
  KEY `idx_parent` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='服务类型表';
DROP TABLE IF EXISTS `t_settlement`;
CREATE TABLE `t_settlement` (
  `settlement_id` varchar(32) NOT NULL COMMENT '结算ID',
  `settlement_no` varchar(50) DEFAULT NULL COMMENT '结算编号',
  `order_id` varchar(32) NOT NULL COMMENT '订单ID',
  `provider_id` varchar(32) DEFAULT NULL COMMENT '服务商ID',
  `staff_id` varchar(32) DEFAULT NULL COMMENT '服务人员ID',
  `elder_id` varchar(32) DEFAULT NULL COMMENT '老人ID',
  `service_date` date DEFAULT NULL COMMENT '服务日期',
  `service_duration` int DEFAULT NULL COMMENT '实际服务时长',
  `unit_price` decimal(10,2) DEFAULT NULL COMMENT '服务单价',
  `total_amount` decimal(10,2) DEFAULT NULL COMMENT '总金额',
  `subsidy_amount` decimal(10,2) DEFAULT NULL COMMENT '补贴金额',
  `self_pay_amount` decimal(10,2) DEFAULT NULL COMMENT '自付金额',
  `payment_method` varchar(20) DEFAULT NULL COMMENT '支付方式 WECHAT/ALIPAY/BANK_CARD/CASH',
  `payment_status` varchar(20) DEFAULT 'UNPAID' COMMENT '支付状态 UNPAID/PAID/REFUNDED',
  `payment_time` datetime DEFAULT NULL COMMENT '支付时间',
  `transaction_id` varchar(100) DEFAULT NULL COMMENT '交易流水号',
  `settlement_time` datetime DEFAULT NULL COMMENT '结算时间',
  `invoice_status` varchar(20) DEFAULT 'NOT_ISSUED' COMMENT '发票状态',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `order_no` varchar(50) DEFAULT NULL COMMENT '订单号',
  `provider_name` varchar(200) DEFAULT NULL COMMENT '服务商名称',
  `staff_name` varchar(50) DEFAULT NULL COMMENT '服务人员姓名',
  `elder_name` varchar(50) DEFAULT NULL COMMENT '老人姓名',
  `settlement_type` varchar(20) DEFAULT NULL COMMENT '结算类型',
  `settlement_amount` decimal(10,2) DEFAULT NULL COMMENT '结算金额',
  `total_order_count` int DEFAULT '0' COMMENT '订单总数',
  `total_service_amount` decimal(10,2) DEFAULT NULL COMMENT '服务费总额',
  `total_subsidy_amount` decimal(10,2) DEFAULT NULL COMMENT '补贴总额',
  `total_self_pay_amount` decimal(10,2) DEFAULT NULL COMMENT '自付总额',
  `settlement_period_start` date DEFAULT NULL COMMENT '结算周期开始',
  `settlement_period_end` date DEFAULT NULL COMMENT '结算周期结束',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `confirm_user_id` varchar(32) DEFAULT NULL COMMENT '确认人ID',
  `confirm_user_name` varchar(50) DEFAULT NULL COMMENT '确认人姓名',
  `confirm_time` datetime DEFAULT NULL COMMENT '确认时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`settlement_id`),
  UNIQUE KEY `settlement_no` (`settlement_no`),
  KEY `idx_order` (`order_id`),
  KEY `idx_provider` (`provider_id`),
  KEY `idx_payment_status` (`payment_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='结算单表';
DROP TABLE IF EXISTS `t_staff`;
CREATE TABLE `t_staff` (
  `staff_id` varchar(32) NOT NULL COMMENT '人员ID',
  `staff_no` varchar(50) DEFAULT NULL COMMENT '人员编号',
  `provider_id` varchar(32) NOT NULL COMMENT '所属服务商ID',
  `staff_name` varchar(50) NOT NULL COMMENT '姓名',
  `gender` varchar(10) DEFAULT NULL COMMENT '性别 MALE/FEMALE',
  `birth_date` date DEFAULT NULL COMMENT '出生日期',
  `age` int DEFAULT NULL COMMENT '年龄',
  `id_card` varchar(18) DEFAULT NULL COMMENT '身份证号',
  `phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `address` varchar(500) DEFAULT NULL COMMENT '家庭住址',
  `emergency_contact` varchar(50) DEFAULT NULL COMMENT '紧急联系人',
  `emergency_phone` varchar(20) DEFAULT NULL COMMENT '紧急联系人电话',
  `education` varchar(20) DEFAULT NULL COMMENT '学历 PRIMARY/JUNIOR/SENIOR/COLLEGE/BACHELOR/MASTER',
  `photo_url` varchar(500) DEFAULT NULL COMMENT '个人照片',
  `status` varchar(20) DEFAULT 'ON_JOB' COMMENT '状态 ON_JOB/LEAVE/QUIT',
  `work_status` varchar(20) DEFAULT 'IDLE' COMMENT '工作状态 IDLE/BUSY/LEAVE',
  `hire_date` date DEFAULT NULL COMMENT '入职日期',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  `provider_name` varchar(200) DEFAULT NULL COMMENT '服务商名称',
  `nation` varchar(20) DEFAULT NULL COMMENT '民族',
  `political_status` varchar(20) DEFAULT NULL COMMENT '政治面貌',
  `marital_status` varchar(10) DEFAULT NULL COMMENT '婚姻状况',
  `domicile_address` varchar(200) DEFAULT NULL COMMENT '户籍地址',
  `residence_address` varchar(200) DEFAULT NULL COMMENT '居住地址',
  `leave_date` date DEFAULT NULL COMMENT '离职日期',
  `leave_reason` varchar(200) DEFAULT NULL COMMENT '离职原因',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `update_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`staff_id`),
  UNIQUE KEY `staff_no` (`staff_no`),
  KEY `idx_staff_no` (`staff_no`),
  KEY `idx_phone` (`phone`),
  KEY `idx_id_card` (`id_card`),
  KEY `idx_provider` (`provider_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='服务人员信息表';
DROP TABLE IF EXISTS `t_staff_qualification`;
CREATE TABLE `t_staff_qualification` (
  `qualification_id` varchar(32) NOT NULL,
  `staff_id` varchar(32) NOT NULL COMMENT '人员ID',
  `qualification_type` varchar(50) DEFAULT NULL COMMENT '资质类型',
  `qualification_name` varchar(200) DEFAULT NULL COMMENT '证书名称',
  `qualification_number` varchar(100) DEFAULT NULL COMMENT '证书编号',
  `issue_date` date DEFAULT NULL COMMENT '发证日期',
  `expiry_date` date DEFAULT NULL COMMENT '有效期至',
  `issue_organization` varchar(200) DEFAULT NULL COMMENT '发证机构',
  `attachment_url` varchar(500) DEFAULT NULL COMMENT '证书扫描件',
  `status` varchar(20) DEFAULT 'VALID' COMMENT '状态',
  `audit_status` varchar(20) DEFAULT 'APPROVED' COMMENT '审核状态',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`qualification_id`),
  KEY `idx_staff` (`staff_id`),
  KEY `idx_expiry` (`expiry_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='服务人员资质表';
DROP TABLE IF EXISTS `t_staff_schedule`;
CREATE TABLE `t_staff_schedule` (
  `schedule_id` varchar(32) NOT NULL,
  `staff_id` varchar(32) NOT NULL,
  `schedule_date` date NOT NULL COMMENT '排班日期',
  `shift_type` varchar(20) DEFAULT NULL COMMENT '班次类型 MORNING/AFTERNOON/EVENING/FULL_DAY',
  `start_time` varchar(10) DEFAULT NULL COMMENT '开始时间',
  `end_time` varchar(10) DEFAULT NULL COMMENT '结束时间',
  `work_area` varchar(200) DEFAULT NULL COMMENT '服务区域',
  `service_types` text COMMENT '服务类型',
  `schedule_status` varchar(20) DEFAULT 'NORMAL' COMMENT '排班状态 NORMAL/LEAVE/ADJUST',
  `remark` text COMMENT '备注',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`schedule_id`),
  KEY `idx_staff` (`staff_id`),
  KEY `idx_date` (`schedule_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='服务人员排班表';
DROP TABLE IF EXISTS `t_staff_work_record`;
CREATE TABLE `t_staff_work_record` (
  `work_record_id` varchar(32) NOT NULL,
  `staff_id` varchar(32) NOT NULL,
  `order_id` varchar(32) DEFAULT NULL COMMENT '订单ID',
  `elder_id` varchar(32) DEFAULT NULL COMMENT '老人ID',
  `service_date` date DEFAULT NULL COMMENT '服务日期',
  `check_in_time` datetime DEFAULT NULL COMMENT '签到时间',
  `check_out_time` datetime DEFAULT NULL COMMENT '签退时间',
  `service_duration` int DEFAULT NULL COMMENT '实际服务时长(分钟)',
  `check_in_location` varchar(500) DEFAULT NULL COMMENT '签到位置',
  `check_out_location` varchar(500) DEFAULT NULL COMMENT '签退位置',
  `service_photos` text COMMENT '服务照片',
  `service_log` text COMMENT '服务日志',
  `abnormal_situation` text COMMENT '异常情况',
  `elder_signature` varchar(500) DEFAULT NULL COMMENT '老人签名',
  `service_status` varchar(20) DEFAULT NULL COMMENT '服务状态',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`work_record_id`),
  KEY `idx_staff` (`staff_id`),
  KEY `idx_order` (`order_id`),
  KEY `idx_date` (`service_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='服务人员工作记录表';
DROP TABLE IF EXISTS `t_system_param`;
CREATE TABLE `t_system_param` (
  `param_id` varchar(32) NOT NULL COMMENT '参数ID',
  `param_category` varchar(50) DEFAULT NULL COMMENT '参数分类',
  `param_code` varchar(100) NOT NULL COMMENT '参数编码',
  `param_name` varchar(100) DEFAULT NULL COMMENT '参数名称',
  `param_value` varchar(500) DEFAULT NULL COMMENT '参数值',
  `param_type` varchar(20) DEFAULT 'STRING' COMMENT '参数类型 STRING/NUMBER/BOOLEAN',
  `default_value` varchar(500) DEFAULT NULL COMMENT '默认值',
  `param_desc` varchar(500) DEFAULT NULL COMMENT '参数说明',
  `is_system` tinyint DEFAULT '0' COMMENT '是否系统参数',
  `sort_order` int DEFAULT NULL COMMENT '排序',
  `status` varchar(20) DEFAULT 'NORMAL' COMMENT '状态',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`param_id`),
  UNIQUE KEY `param_code` (`param_code`),
  KEY `idx_param_code` (`param_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='系统参数表';
DROP TABLE IF EXISTS `t_user`;
CREATE TABLE `t_user` (
  `user_id` varchar(32) NOT NULL COMMENT '用户ID',
  `username` varchar(50) NOT NULL COMMENT '用户名',
  `password` varchar(200) NOT NULL COMMENT '密码(BCrypt加密)',
  `real_name` varchar(50) DEFAULT NULL COMMENT '真实姓名',
  `phone` varchar(20) DEFAULT NULL COMMENT '手机号',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `gender` varchar(10) DEFAULT NULL COMMENT '性别',
  `avatar` varchar(500) DEFAULT NULL COMMENT '头像URL',
  `user_type` varchar(20) DEFAULT NULL COMMENT '用户类型 SYSTEM/ADMIN/PROVIDER/STAFF',
  `status` varchar(20) DEFAULT 'NORMAL' COMMENT '状态 NORMAL/DISABLED/LOCKED',
  `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
  `last_login_ip` varchar(50) DEFAULT NULL COMMENT '最后登录IP',
  `login_fail_count` int DEFAULT '0' COMMENT '登录失败次数',
  `lock_time` datetime DEFAULT NULL COMMENT '锁定时间',
  `tenant_id` varchar(32) DEFAULT NULL COMMENT '租户ID',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记',
  `provider_id` varchar(32) DEFAULT NULL COMMENT '服务商ID',
  `staff_id` varchar(32) DEFAULT NULL COMMENT '服务人员ID',
  `area_id` varchar(32) DEFAULT NULL COMMENT '区域ID',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `username` (`username`),
  KEY `idx_username` (`username`),
  KEY `idx_phone` (`phone`),
  KEY `idx_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户表';
DROP TABLE IF EXISTS `t_user_role`;
CREATE TABLE `t_user_role` (
  `user_role_id` varchar(32) NOT NULL,
  `user_id` varchar(32) NOT NULL COMMENT '用户ID',
  `role_id` varchar(32) NOT NULL COMMENT '角色ID',
  `area_id` varchar(32) DEFAULT NULL COMMENT '区域ID',
  `tenant_id` varchar(32) DEFAULT NULL COMMENT '租户ID',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_role_id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_role` (`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户角色关联表';


