/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/__builtin/403/index.vue"),
  404: () => import("@/views/__builtin/404/index.vue"),
  500: () => import("@/views/__builtin/500/index.vue"),
  "iframe-page": () => import("@/views/__builtin/iframe-page/[url].vue"),
  login: () => import("@/views/__builtin/login/index.vue"),
  appointment: () => import("@/views/appointment/index.vue"),
  "builtin_rd-report": () => import("@/views/builtin/rd-report/index.vue"),
  business_contract: () => import("@/views/business/contract/index.vue"),
  business_elder: () => import("@/views/business/elder/index.vue"),
  business_evaluation: () => import("@/views/business/evaluation/index.vue"),
  business_financial: () => import("@/views/business/financial/index.vue"),
  "business_health-archive": () => import("@/views/business/health-archive/index.vue"),
  business_order: () => import("@/views/business/order/index.vue"),
  business_quality: () => import("@/views/business/quality/index.vue"),
  "business_service-log": () => import("@/views/business/service-log/index.vue"),
  business_staff: () => import("@/views/business/staff/index.vue"),
  home: () => import("@/views/home/index.vue"),
  provider: () => import("@/views/provider/index.vue"),
  "public_appointment-book": () => import("@/views/public/appointment-book/index.vue"),
  public_dashboard: () => import("@/views/public/dashboard/index.vue"),
  public_mobile: () => import("@/views/public/mobile/index.vue"),
  public_survey: () => import("@/views/public/survey/index.vue"),
  system_dict: () => import("@/views/system/dict/index.vue"),
  system_menu: () => import("@/views/system/menu/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
};
