/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'appointment',
    path: '/appointment',
    component: 'layout.base$view.appointment',
    meta: {
      title: 'appointment',
      i18nKey: 'route.appointment',
      icon: 'mdi:calendar-clock',
      order: 2
    }
  },
  {
    name: 'business',
    path: '/business',
    component: 'layout.base',
    meta: {
      title: 'business',
      i18nKey: 'route.business',
      icon: 'mdi:briefcase-outline',
      order: 5
    },
    children: [
      {
        name: 'business_contract',
        path: '/business/contract',
        component: 'view.business_contract',
        meta: {
          title: 'business_contract',
          i18nKey: 'route.business_contract'
        }
      },
      {
        name: 'business_elder',
        path: '/business/elder',
        component: 'view.business_elder',
        meta: {
          title: 'business_elder',
          i18nKey: 'route.business_elder',
          icon: 'mdi:human-handsup',
          order: 4
        }
      },
      {
        name: 'business_evaluation',
        path: '/business/evaluation',
        component: 'view.business_evaluation',
        meta: {
          title: 'business_evaluation',
          i18nKey: 'route.business_evaluation',
          icon: 'mdi:star-check',
          order: 9
        }
      },
      {
        name: 'business_financial',
        path: '/business/financial',
        component: 'view.business_financial',
        meta: {
          title: 'business_financial',
          i18nKey: 'route.business_financial',
          icon: 'mdi:cash-multiple',
          order: 10
        }
      },
      {
        name: 'business_health-archive',
        path: '/business/health-archive',
        component: 'view.business_health-archive',
        meta: {
          title: 'business_healthArchive',
          i18nKey: 'route.business_healthArchive',
          icon: 'mdi:heart-pulse',
          order: 5
        }
      },
      {
        name: 'business_order',
        path: '/business/order',
        component: 'view.business_order',
        meta: {
          title: 'business_order',
          i18nKey: 'route.business_order',
          icon: 'mdi:clipboard-list',
          order: 3
        }
      },
      {
        name: 'business_quality',
        path: '/business/quality',
        component: 'view.business_quality',
        meta: {
          title: 'business_quality',
          i18nKey: 'route.business_quality',
          icon: 'mdi:clipboard-check-outline',
          order: 8
        }
      },
      {
        name: 'business_service-log',
        path: '/business/service-log',
        component: 'view.business_service-log',
        meta: {
          title: 'business_service-log',
          i18nKey: 'route.business_service-log',
          icon: 'mdi:clipboard-text-clock',
          order: 7
        }
      },
      {
        name: 'business_staff',
        path: '/business/staff',
        component: 'view.business_staff',
        meta: {
          title: 'business_staff',
          i18nKey: 'route.business_staff',
          icon: 'mdi:account-tie',
          order: 6
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'provider',
    path: '/provider',
    component: 'layout.base$view.provider',
    meta: {
      title: 'provider',
      i18nKey: 'route.provider',
      icon: 'mdi:domain',
      order: 4
    }
  },
  {
    name: 'public',
    path: '/public',
    component: 'layout.base',
    meta: {
      title: 'public',
      i18nKey: 'route.public'
    },
    children: [
      {
        name: 'public_appointment-book',
        path: '/public/appointment-book',
        component: 'view.public_appointment-book',
        meta: {
          title: 'public_appointment-book',
          i18nKey: 'route.public_appointment-book'
        }
      },
      {
        name: 'public_dashboard',
        path: '/public/dashboard',
        component: 'view.public_dashboard',
        meta: {
          title: 'public_dashboard',
          i18nKey: 'route.public_dashboard'
        }
      },
      {
        name: 'public_mobile',
        path: '/public/mobile',
        component: 'view.public_mobile',
        meta: {
          title: 'public_mobile',
          i18nKey: 'route.public_mobile'
        }
      },
      {
        name: 'public_survey',
        path: '/public/survey',
        component: 'view.public_survey',
        meta: {
          title: 'public_survey',
          i18nKey: 'route.public_survey'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'mdi:cog-outline',
      order: 6
    },
    children: [
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict',
          icon: 'mdi:book-alphabet',
          order: 3
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu',
          icon: 'mdi:menu',
          order: 2
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role',
          icon: 'mdi:shield-account',
          order: 4
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user',
          icon: 'mdi:account-group',
          order: 5
        }
      }
    ]
  }
];
