/* eslint-disable */
// @ts-nocheck
/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

export {}

declare module "vue-router" {
  type RouteNamedMap = import("vue-router/auto-routes").RouteNamedMap;

  export interface TypesConfig {
    RouteNamedMap: RouteNamedMap;
  }
}

declare module "vue-router/auto-routes" {
  import type { RouteParamsRawGeneric, RouteParamsGeneric, RouteMeta, RouteRecordInfo, ParamValue, ParamValueZeroOrOne } from "vue-router";

  /**
   * route named map
  */
  export interface RouteNamedMap {
    "Root": RouteRecordInfo<"Root", "/", Record<never, never>, Record<never, never>>;
    "NotFound": RouteRecordInfo<"NotFound", "/:pathMatch(.*)*", Record<never, never>, Record<never, never>>;
    "_Builtin403": RouteRecordInfo<"_Builtin403", "/__builtin/403", Record<never, never>, Record<never, never>>;
    "_Builtin404": RouteRecordInfo<"_Builtin404", "/__builtin/404", Record<never, never>, Record<never, never>>;
    "_Builtin500": RouteRecordInfo<"_Builtin500", "/__builtin/500", Record<never, never>, Record<never, never>>;
    "_BuiltinIframePageUrl": RouteRecordInfo<"_BuiltinIframePageUrl", "/__builtin/iframe-page/:url", { url: ParamValue<true> }, { url: ParamValue<false> }>;
    "_BuiltinLogin": RouteRecordInfo<"_BuiltinLogin", "/__builtin/login", Record<never, never>, Record<never, never>>;
    "Appointment": RouteRecordInfo<"Appointment", "/appointment", Record<never, never>, Record<never, never>>;
    "Builtin403": RouteRecordInfo<"Builtin403", "/builtin/403", Record<never, never>, Record<never, never>>;
    "Builtin404": RouteRecordInfo<"Builtin404", "/builtin/404", Record<never, never>, Record<never, never>>;
    "Builtin500": RouteRecordInfo<"Builtin500", "/builtin/500", Record<never, never>, Record<never, never>>;
    "BuiltinIframePageUrl": RouteRecordInfo<"BuiltinIframePageUrl", "/builtin/iframe-page/:url", { url: ParamValue<true> }, { url: ParamValue<false> }>;
    "BuiltinLogin": RouteRecordInfo<"BuiltinLogin", "/builtin/login", Record<never, never>, Record<never, never>>;
    "BuiltinRdReport": RouteRecordInfo<"BuiltinRdReport", "/builtin/rd-report", Record<never, never>, Record<never, never>>;
    "BusinessContract": RouteRecordInfo<"BusinessContract", "/business/contract", Record<never, never>, Record<never, never>>;
    "BusinessElder": RouteRecordInfo<"BusinessElder", "/business/elder", Record<never, never>, Record<never, never>>;
    "BusinessEvaluation": RouteRecordInfo<"BusinessEvaluation", "/business/evaluation", Record<never, never>, Record<never, never>>;
    "BusinessFinancial": RouteRecordInfo<"BusinessFinancial", "/business/financial", Record<never, never>, Record<never, never>>;
    "BusinessHealthArchive": RouteRecordInfo<"BusinessHealthArchive", "/business/health-archive", Record<never, never>, Record<never, never>>;
    "BusinessOrder": RouteRecordInfo<"BusinessOrder", "/business/order", Record<never, never>, Record<never, never>>;
    "BusinessQuality": RouteRecordInfo<"BusinessQuality", "/business/quality", Record<never, never>, Record<never, never>>;
    "BusinessServiceLog": RouteRecordInfo<"BusinessServiceLog", "/business/service-log", Record<never, never>, Record<never, never>>;
    "BusinessStaff": RouteRecordInfo<"BusinessStaff", "/business/staff", Record<never, never>, Record<never, never>>;
    "Home": RouteRecordInfo<"Home", "/home", Record<never, never>, Record<never, never>>;
    "Provider": RouteRecordInfo<"Provider", "/provider", Record<never, never>, Record<never, never>>;
    "PublicAppointmentBook": RouteRecordInfo<"PublicAppointmentBook", "/public/appointment-book", Record<never, never>, Record<never, never>>;
    "PublicDashboard": RouteRecordInfo<"PublicDashboard", "/public/dashboard", Record<never, never>, Record<never, never>>;
    "PublicMobile": RouteRecordInfo<"PublicMobile", "/public/mobile", Record<never, never>, Record<never, never>>;
    "PublicSurvey": RouteRecordInfo<"PublicSurvey", "/public/survey", Record<never, never>, Record<never, never>>;
    "SharedCockpitElderAnalysis": RouteRecordInfo<"SharedCockpitElderAnalysis", "/shared/cockpit/ElderAnalysis", Record<never, never>, Record<never, never>>;
    "SharedCockpitFinancialAnalysis": RouteRecordInfo<"SharedCockpitFinancialAnalysis", "/shared/cockpit/FinancialAnalysis", Record<never, never>, Record<never, never>>;
    "SharedCockpitOrderAnalysis": RouteRecordInfo<"SharedCockpitOrderAnalysis", "/shared/cockpit/OrderAnalysis", Record<never, never>, Record<never, never>>;
    "SharedCockpitQualityAnalysis": RouteRecordInfo<"SharedCockpitQualityAnalysis", "/shared/cockpit/QualityAnalysis", Record<never, never>, Record<never, never>>;
    "SystemDict": RouteRecordInfo<"SystemDict", "/system/dict", Record<never, never>, Record<never, never>>;
    "SystemMenu": RouteRecordInfo<"SystemMenu", "/system/menu", Record<never, never>, Record<never, never>>;
    "SystemRole": RouteRecordInfo<"SystemRole", "/system/role", Record<never, never>, Record<never, never>>;
    "SystemUser": RouteRecordInfo<"SystemUser", "/system/user", Record<never, never>, Record<never, never>>
  }
}
